package com.echo.common

object Constants {
    const val SPLASH_DELAY = 1500L
    const val PREF_NAME = "my pref"
    const val ONBOARDING_PREF = "oboarding_pref"
    const val OnBoarding_LAST_FRAGMENT_INDEX = 2
    const val REQUEST_CODE_LOCATION_PERMISSION = 10
    const val PERMISSION_LOCATION_REQUEST_CODE=1
    const val BACKGROUND_PERMISSION_LOCATION_REQUEST_CODE=2

    const val NOTIFICATION_CHANNEL_ID="NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME="NOTIFICATION_CHANNEL_NAME"
    const val NOTIFICATION_ID=3

    const val ACTION_START_FOREGROUND_SERVICE="ACTION_START_FOREGROUND_SERVICE"
    const val ACTION_STOP_FOREGROUND_SERVICE="ACTION_STOP_FOREGROUND_SERVICE"

    const val LOCATION_UPDATE_INTERVAL=4000L
    const val LOCATION_FASTEST_UPDATE_INTERVAL=2000L
    const val GOOGLE_API_KEY = "AIzaSyBWh7Fah-LINDZ3Ppf17d7-ht7OGSrjOhA"
}